---
namespace: tpajon

name: aos

version: 1.0.2

readme: README.md

authors:
- tpajon <https://github.com/tpajon>

description: An Aruba OS Switches collection

license_file: 'LICENSE'

tags: ['tpajon', 'aos', 'aruba', 'arubaos', 'switch', 'networking', 'network']

dependencies:
  "ansible.netcommon": ">=2.0.1"

repository: https://github.com/tpajon/aos.git

issues: https://github.com/tpajon/aos/issues
